/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I'/home/oakenbow/.choosenim/toolchains/nim-#devel/lib' -o /home/oakenbow/Dev/Projects/desktop-parser-nim/src/nimcache/desktop_parser_nim_desktop_parser_nim.o /home/oakenbow/Dev/Projects/desktop-parser-nim/src/nimcache/desktop_parser_nim_desktop_parser_nim.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <dirent.h>
#include <setjmp.h>
#include <sys/types.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_LCURwohbLBusrL8hdCnvng tyTuple_LCURwohbLBusrL8hdCnvng;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A;
typedef struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NU8 tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg;
struct tyTuple_LCURwohbLBusrL8hdCnvng {
tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg Field0;
NimStringDesc* Field1;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef char tyArray_XKk9bNZbVEtY3RuROG9aRBgw[256];
typedef long tyArray_QS4edQct6fXoghbs69aZ9a8w[3];
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NimStringDesc* tyArray_haiLFy0nBviVTKFGuwztzQ[5];
struct tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw {
tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* h;
tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ* e;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A {
char dummy;
};
struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ {
long flags;
void* study_data;
long match_limit;
void* callout_data;
void* tables;
long match_limit_recursion;
void* mark;
void* executable_jit;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_6)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*, re_2TnOqvPvxix6tRYnuIeq9bw)(NimStringDesc* s, tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg flags);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_8)(void);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_10)(void);
N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringDesc* dir);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_13)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogdesktop_parser_nim)(NimStringDesc* dir);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_14)(void);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(NIM_BOOL, fileExists_yTPrfdEKg9cKCeSFUA6popQdesktop_parser_nim)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_18)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readAll_y7iEIBoIrYlvsLCqA1SrwQ)(FILE* file);
N_LIB_PRIVATE N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_19)(void);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_20)(void);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_21)(void);
static N_INLINE(NI, find_SG5PU3DKAXRWI7vCeKQOCQ_2re)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start);
N_LIB_PRIVATE N_NIMCALL(NI, find_h9b0CsNbjKuk9c6lgvmZ9bbWQ)(NCSTRING buf, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, replace_XTFad3adT9ckW2xJiSYMhMw)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg, getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg)(NimStringDesc* path);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_27)(void);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_28)(void);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_29)(void);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_30)(void);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, desktop_parser_nimDatInit000)(void);
tyArray_Re75IspeoxXy2oCZHwcRrA dirs_5wY9cXAWXrm4ulzUOhfXisA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_Re75IspeoxXy2oCZHwcRrA_;
tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* namePattern_7TZVn5lrFxsCgyGkIvtdgw;
extern TNimType NTI_dkhOdInu11QXB2HnNpgmJQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* execPattern_umckWp8Z39aRjyxuzyRpR9cA;
tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* argPattern_0utS3ILD5VWCsdlXu6g89aQ;
NimStringDesc* dir_ALLee4kFrceaPHAJbX0qxg;
tyTuple_LCURwohbLBusrL8hdCnvng filePath_6qiqGr9a0Aux4l9bbz9ayunRg;
extern TNimType NTI_LCURwohbLBusrL8hdCnvng_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
NimStringDesc* file_ltpyxdRnkwZ4h3HRLHHKNw;
NimStringDesc* name_QBA15VCUqOaVIF7pPjoJig;
NimStringDesc* exec_VvPIpxxrGablvcaz7nQNGA;
tyArray_nHXaesL0DJZHyVS07ARPRA matches_xtEppuDcq6NTpHRJimET8g;
TNimType NTI_nHXaesL0DJZHyVS07ARPRA_;
FILE* execFile_GbPldOFJWq0i88ldXmT74w;
NimStringDesc* file_ltpyxdRnkwZ4h3HRLHHKNw_2;
NimStringDesc* name_QBA15VCUqOaVIF7pPjoJig_2;
NimStringDesc* exec_VvPIpxxrGablvcaz7nQNGA_2;
tyArray_nHXaesL0DJZHyVS07ARPRA matches_xtEppuDcq6NTpHRJimET8g_2;
FILE* execFile_GbPldOFJWq0i88ldXmT74w_2;
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_4, "/usr/share/applications", 23);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_5, "~/.local/share/applications", 27);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Y9cGof9b2sgVva5jpid59aDNQ_3 = {((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_4),
((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_5)}
;
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_7, "Name=(.*)", 9);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_9, "Exec=(.*)", 9);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_11, "%([a-z]|[A-Z])", 14);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_12, "./execs", 7);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_16, ".", 1);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_17, "..", 2);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_22, "", 0);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_23, "Found app \'", 11);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_24, "\' with exec \'", 13);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_25, "\'", 1);
STRING_LITERAL(TM_Y9cGof9b2sgVva5jpid59aDNQ_26, "./execs/", 8);
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_2)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 2; T1_++) {
	nimGCvisit((void*)dirs_5wY9cXAWXrm4ulzUOhfXisA[T1_], 0);
	}
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_6)(void) {
	nimGCvisit((void*)namePattern_7TZVn5lrFxsCgyGkIvtdgw, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_8)(void) {
	nimGCvisit((void*)execPattern_umckWp8Z39aRjyxuzyRpR9cA, 0);
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_10)(void) {
	nimGCvisit((void*)argPattern_0utS3ILD5VWCsdlXu6g89aQ, 0);
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_13)(void) {
	nimGCvisit((void*)dir_ALLee4kFrceaPHAJbX0qxg, 0);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogdesktop_parser_nim)(NimStringDesc* dir) {
	NIM_BOOL result;
	nimfr_("dirExists", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(119, "os.nim");
	nimln_(120, "os.nim");
	result = nosexistsDir(dir);
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_14)(void) {
	nimGCvisit((void*)filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field1, 0);
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, fileExists_yTPrfdEKg9cKCeSFUA6popQdesktop_parser_nim)(NimStringDesc* filename) {
	NIM_BOOL result;
	nimfr_("fileExists", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(115, "os.nim");
	nimln_(116, "os.nim");
	result = nosexistsFile(filename);
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_18)(void) {
	nimGCvisit((void*)file_ltpyxdRnkwZ4h3HRLHHKNw, 0);
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_19)(void) {
	nimGCvisit((void*)name_QBA15VCUqOaVIF7pPjoJig, 0);
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_20)(void) {
	nimGCvisit((void*)exec_VvPIpxxrGablvcaz7nQNGA, 0);
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_21)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 1; T1_++) {
	nimGCvisit((void*)matches_xtEppuDcq6NTpHRJimET8g[T1_], 0);
	}
}

static N_INLINE(NI, find_SG5PU3DKAXRWI7vCeKQOCQ_2re)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start) {
	NI result;
	nimfr_("find", "re.nim");
	result = (NI)0;
	nimln_(298, "re.nim");
	result = find_h9b0CsNbjKuk9c6lgvmZ9bbWQ(s->data, pattern, matches, matchesLen_0, start, (s ? s->Sup.len : 0));
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_27)(void) {
	nimGCvisit((void*)file_ltpyxdRnkwZ4h3HRLHHKNw_2, 0);
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_28)(void) {
	nimGCvisit((void*)name_QBA15VCUqOaVIF7pPjoJig_2, 0);
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_29)(void) {
	nimGCvisit((void*)exec_VvPIpxxrGablvcaz7nQNGA_2, 0);
}
static N_NIMCALL(void, TM_Y9cGof9b2sgVva5jpid59aDNQ_30)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 1; T1_++) {
	nimGCvisit((void*)matches_xtEppuDcq6NTpHRJimET8g_2[T1_], 0);
	}
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_pcreDatInit000();
	stdlib_rtarraysDatInit000();
	stdlib_reDatInit000();
	desktop_parser_nimDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_pcreInit000();
	stdlib_rtarraysInit000();
	stdlib_reInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("desktop_parser_nim", "desktop_parser_nim.nim");
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_2);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_6);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_8);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_10);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_13);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_14);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_18);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_19);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_20);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_21);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_27);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_28);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_29);
nimRegisterGlobalMarker(TM_Y9cGof9b2sgVva5jpid59aDNQ_30);
	nimln_(5, "desktop_parser_nim.nim");
	genericAssign((void*)dirs_5wY9cXAWXrm4ulzUOhfXisA, (void*)TM_Y9cGof9b2sgVva5jpid59aDNQ_3, (&NTI_Re75IspeoxXy2oCZHwcRrA_));
	nimln_(6, "desktop_parser_nim.nim");
	asgnRefNoCycle((void**) (&namePattern_7TZVn5lrFxsCgyGkIvtdgw), re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_7), 16));
	nimln_(7, "desktop_parser_nim.nim");
	asgnRefNoCycle((void**) (&execPattern_umckWp8Z39aRjyxuzyRpR9cA), re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_9), 16));
	nimln_(8, "desktop_parser_nim.nim");
	asgnRefNoCycle((void**) (&argPattern_0utS3ILD5VWCsdlXu6g89aQ), re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_11), 16));
	nimln_(10, "desktop_parser_nim.nim");
	noscreateDir(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_12));
	{
		NI i;
		nimln_(2199, "system.nim");
		i = ((NI) 0);
		nimln_(2200, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 1))) goto LA4_;
			{
				nimln_(2201, "system.nim");
				while (1) {
					NimStringDesc* T8_;
					NI TM_Y9cGof9b2sgVva5jpid59aDNQ_31;
					nimln_(2202, "system.nim");
					T8_ = (NimStringDesc*)0;
					T8_ = dir_ALLee4kFrceaPHAJbX0qxg; dir_ALLee4kFrceaPHAJbX0qxg = copyStringRC1(dirs_5wY9cXAWXrm4ulzUOhfXisA[(i)- 0]);
					if (T8_) nimGCunrefNoCycle(T8_);
					{
						nimln_(13, "desktop_parser_nim.nim");
						{
							NIM_BOOL T12_;
							T12_ = (NIM_BOOL)0;
							T12_ = dirExists_wf0Ae3eLXw0lSNEFJMV3ogdesktop_parser_nim(dir_ALLee4kFrceaPHAJbX0qxg);
							if (!!(T12_)) goto LA13_;
							nimln_(14, "desktop_parser_nim.nim");
							goto LA9;
						}
						LA13_: ;
						{
							DIR* d;
							chckNil((void*)(&filePath_6qiqGr9a0Aux4l9bbz9ayunRg));
							genericReset((void*)(&filePath_6qiqGr9a0Aux4l9bbz9ayunRg), (&NTI_LCURwohbLBusrL8hdCnvng_));
							nimln_(798, "os.nim");
							d = opendir(dir_ALLee4kFrceaPHAJbX0qxg->data);
							nimln_(799, "os.nim");
							{
								TSafePoint TM_Y9cGof9b2sgVva5jpid59aDNQ_15;
								nimln_(398, "system.nim");
								nimln_(799, "os.nim");
								if (!!((d == NIM_NIL))) goto LA18_;
								nimln_(800, "os.nim");
								pushSafePoint(&TM_Y9cGof9b2sgVva5jpid59aDNQ_15);
								TM_Y9cGof9b2sgVva5jpid59aDNQ_15.status = setjmp(TM_Y9cGof9b2sgVva5jpid59aDNQ_15.context);
								if (TM_Y9cGof9b2sgVva5jpid59aDNQ_15.status == 0) {
									{
										nimln_(801, "os.nim");
										while (1) {
											{
												struct dirent* x;
												NimStringDesc* volatile y;
												nimln_(802, "os.nim");
												x = readdir(d);
												nimln_(803, "os.nim");
												{
													if (!(x == NIM_NIL)) goto LA26_;
													goto LA21;
												}
												LA26_: ;
												nimln_(805, "os.nim");
												y = cstrToNimstr(((NCSTRING) ((*x).d_name)));
												nimln_(808, "os.nim");
												{
													NIM_BOOL T30_;
													struct stat s;
													tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg volatile k;
													NimStringDesc* T100_;
													T30_ = (NIM_BOOL)0;
													nimln_(398, "system.nim");
													nimln_(808, "os.nim");
													T30_ = !(eqStrings(y, ((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_16)));
													if (!(T30_)) goto LA31_;
													nimln_(398, "system.nim");
													nimln_(808, "os.nim");
													T30_ = !(eqStrings(y, ((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_17)));
													LA31_: ;
													if (!T30_) goto LA32_;
													memset((void*)(&s), 0, sizeof(s));
													nimln_(810, "os.nim");
													{
														if (!NIM_TRUE) goto LA36_;
														nimln_(811, "os.nim");
														y = slash__lXoMhn1ZYc9cAJa9bfA61msg(dir_ALLee4kFrceaPHAJbX0qxg, y);
													}
													LA36_: ;
													nimln_(812, "os.nim");
													k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0);
													nimln_(815, "os.nim");
													{
														NimStringDesc* T56_;
														nimln_(398, "system.nim");
														nimln_(815, "os.nim");
														if (!!(((*x).d_type == ((NI8) 0)))) goto LA40_;
														nimln_(816, "os.nim");
														{
															if (!((*x).d_type == ((NI8) 4))) goto LA44_;
															k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
														}
														LA44_: ;
														nimln_(817, "os.nim");
														{
															if (!((*x).d_type == ((NI8) 10))) goto LA48_;
															nimln_(818, "os.nim");
															{
																NIM_BOOL T52_;
																T52_ = (NIM_BOOL)0;
																T52_ = dirExists_wf0Ae3eLXw0lSNEFJMV3ogdesktop_parser_nim(y);
																if (!T52_) goto LA53_;
																k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3);
															}
															goto LA50_;
															LA53_: ;
															{
																nimln_(819, "os.nim");
																k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1);
															}
															LA50_: ;
														}
														LA48_: ;
														nimln_(820, "os.nim");
														filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field0 = k;
														T56_ = (NimStringDesc*)0;
														T56_ = filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field1; filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field1 = copyStringRC1(y);
														if (T56_) nimGCunrefNoCycle(T56_);
														{
															FILE* T63_;
															NimStringDesc* T69_;
															NimStringDesc* T79_;
															tyArray_haiLFy0nBviVTKFGuwztzQ T84_;
															NimStringDesc* T85_;
															nimln_(17, "desktop_parser_nim.nim");
															{
																NIM_BOOL T60_;
																T60_ = (NIM_BOOL)0;
																T60_ = fileExists_yTPrfdEKg9cKCeSFUA6popQdesktop_parser_nim(filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field1);
																if (!!(T60_)) goto LA61_;
																goto LA57;
															}
															LA61_: ;
															asgnRefNoCycle((void**) (&file_ltpyxdRnkwZ4h3HRLHHKNw), NIM_NIL);
															nimln_(18, "desktop_parser_nim.nim");
															T63_ = (FILE*)0;
															T63_ = open_hqzpWQbdA2B8l9a6wwNoP4g(filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field1, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
															asgnRefNoCycle((void**) (&file_ltpyxdRnkwZ4h3HRLHHKNw), readAll_y7iEIBoIrYlvsLCqA1SrwQ(T63_));
															asgnRefNoCycle((void**) (&name_QBA15VCUqOaVIF7pPjoJig), NIM_NIL);
															asgnRefNoCycle((void**) (&exec_VvPIpxxrGablvcaz7nQNGA), NIM_NIL);
															chckNil((void*)matches_xtEppuDcq6NTpHRJimET8g);
															genericReset((void*)matches_xtEppuDcq6NTpHRJimET8g, (&NTI_nHXaesL0DJZHyVS07ARPRA_));
															nimln_(22, "desktop_parser_nim.nim");
															{
																NI T66_;
																T66_ = (NI)0;
																T66_ = find_SG5PU3DKAXRWI7vCeKQOCQ_2re(file_ltpyxdRnkwZ4h3HRLHHKNw, namePattern_7TZVn5lrFxsCgyGkIvtdgw, matches_xtEppuDcq6NTpHRJimET8g, 1, ((NI) 0));
																if (!(T66_ == ((NI) -1))) goto LA67_;
																goto LA57;
															}
															LA67_: ;
															nimln_(23, "desktop_parser_nim.nim");
															T69_ = (NimStringDesc*)0;
															T69_ = name_QBA15VCUqOaVIF7pPjoJig; name_QBA15VCUqOaVIF7pPjoJig = copyStringRC1(matches_xtEppuDcq6NTpHRJimET8g[(((NI) 0))- 0]);
															if (T69_) nimGCunrefNoCycle(T69_);
															nimln_(24, "desktop_parser_nim.nim");
															{
																if (!((name_QBA15VCUqOaVIF7pPjoJig ? name_QBA15VCUqOaVIF7pPjoJig->Sup.len : 0) == ((NI) 0))) goto LA72_;
																goto LA57;
															}
															LA72_: ;
															nimln_(25, "desktop_parser_nim.nim");
															{
																NI T76_;
																T76_ = (NI)0;
																T76_ = find_SG5PU3DKAXRWI7vCeKQOCQ_2re(file_ltpyxdRnkwZ4h3HRLHHKNw, execPattern_umckWp8Z39aRjyxuzyRpR9cA, matches_xtEppuDcq6NTpHRJimET8g, 1, ((NI) 0));
																if (!(T76_ == ((NI) -1))) goto LA77_;
																goto LA57;
															}
															LA77_: ;
															nimln_(26, "desktop_parser_nim.nim");
															T79_ = (NimStringDesc*)0;
															T79_ = exec_VvPIpxxrGablvcaz7nQNGA; exec_VvPIpxxrGablvcaz7nQNGA = copyStringRC1(matches_xtEppuDcq6NTpHRJimET8g[(((NI) 0))- 0]);
															if (T79_) nimGCunrefNoCycle(T79_);
															nimln_(27, "desktop_parser_nim.nim");
															{
																if (!((exec_VvPIpxxrGablvcaz7nQNGA ? exec_VvPIpxxrGablvcaz7nQNGA->Sup.len : 0) == ((NI) 0))) goto LA82_;
																goto LA57;
															}
															LA82_: ;
															nimln_(28, "desktop_parser_nim.nim");
															asgnRefNoCycle((void**) (&exec_VvPIpxxrGablvcaz7nQNGA), replace_XTFad3adT9ckW2xJiSYMhMw(exec_VvPIpxxrGablvcaz7nQNGA, argPattern_0utS3ILD5VWCsdlXu6g89aQ, ((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_22)));
															nimln_(30, "desktop_parser_nim.nim");
															memset((void*)T84_, 0, sizeof(T84_));
															T84_[0] = copyString(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_23));
															T84_[1] = copyString(name_QBA15VCUqOaVIF7pPjoJig);
															T84_[2] = copyString(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_24));
															T84_[3] = copyString(exec_VvPIpxxrGablvcaz7nQNGA);
															T84_[4] = copyString(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_25));
															echoBinSafe(T84_, 5);
															execFile_GbPldOFJWq0i88ldXmT74w = 0;
															nimln_(31, "desktop_parser_nim.nim");
															T85_ = (NimStringDesc*)0;
															T85_ = rawNewString(name_QBA15VCUqOaVIF7pPjoJig->Sup.len + 8);
appendString(T85_, ((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_26));
appendString(T85_, name_QBA15VCUqOaVIF7pPjoJig);
															execFile_GbPldOFJWq0i88ldXmT74w = open_hqzpWQbdA2B8l9a6wwNoP4g(T85_, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
															nimln_(32, "desktop_parser_nim.nim");
															write_c4mGyJBvK73pdM22jiweKQ(execFile_GbPldOFJWq0i88ldXmT74w, exec_VvPIpxxrGablvcaz7nQNGA);
															nimln_(33, "desktop_parser_nim.nim");
															close_BWnr8V7RERYno9bIdPmw8Hw_2(execFile_GbPldOFJWq0i88ldXmT74w);
														} LA57: ;
														nimln_(821, "os.nim");
														goto LA23;
													}
													LA40_: ;
													nimln_(823, "os.nim");
													{
														int T88_;
														T88_ = (int)0;
														T88_ = lstat(y->data, (&s));
														if (!(T88_ < ((NI32) 0))) goto LA89_;
														goto LA21;
													}
													LA89_: ;
													nimln_(824, "os.nim");
													{
														NIM_BOOL T93_;
														T93_ = (NIM_BOOL)0;
														T93_ = S_ISDIR(s.st_mode);
														if (!T93_) goto LA94_;
														nimln_(825, "os.nim");
														k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
													}
													goto LA91_;
													LA94_: ;
													{
														NIM_BOOL T97_;
														nimln_(826, "os.nim");
														T97_ = (NIM_BOOL)0;
														T97_ = S_ISLNK(s.st_mode);
														if (!T97_) goto LA98_;
														nimln_(827, "os.nim");
														k = getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg(y);
													}
													goto LA91_;
													LA98_: ;
													LA91_: ;
													nimln_(828, "os.nim");
													filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field0 = k;
													T100_ = (NimStringDesc*)0;
													T100_ = filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field1; filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field1 = copyStringRC1(y);
													if (T100_) nimGCunrefNoCycle(T100_);
													{
														FILE* T107_;
														NimStringDesc* T113_;
														NimStringDesc* T123_;
														tyArray_haiLFy0nBviVTKFGuwztzQ T128_;
														NimStringDesc* T129_;
														nimln_(17, "desktop_parser_nim.nim");
														{
															NIM_BOOL T104_;
															T104_ = (NIM_BOOL)0;
															T104_ = fileExists_yTPrfdEKg9cKCeSFUA6popQdesktop_parser_nim(filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field1);
															if (!!(T104_)) goto LA105_;
															goto LA101;
														}
														LA105_: ;
														asgnRefNoCycle((void**) (&file_ltpyxdRnkwZ4h3HRLHHKNw_2), NIM_NIL);
														nimln_(18, "desktop_parser_nim.nim");
														T107_ = (FILE*)0;
														T107_ = open_hqzpWQbdA2B8l9a6wwNoP4g(filePath_6qiqGr9a0Aux4l9bbz9ayunRg.Field1, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
														asgnRefNoCycle((void**) (&file_ltpyxdRnkwZ4h3HRLHHKNw_2), readAll_y7iEIBoIrYlvsLCqA1SrwQ(T107_));
														asgnRefNoCycle((void**) (&name_QBA15VCUqOaVIF7pPjoJig_2), NIM_NIL);
														asgnRefNoCycle((void**) (&exec_VvPIpxxrGablvcaz7nQNGA_2), NIM_NIL);
														chckNil((void*)matches_xtEppuDcq6NTpHRJimET8g_2);
														genericReset((void*)matches_xtEppuDcq6NTpHRJimET8g_2, (&NTI_nHXaesL0DJZHyVS07ARPRA_));
														nimln_(22, "desktop_parser_nim.nim");
														{
															NI T110_;
															T110_ = (NI)0;
															T110_ = find_SG5PU3DKAXRWI7vCeKQOCQ_2re(file_ltpyxdRnkwZ4h3HRLHHKNw_2, namePattern_7TZVn5lrFxsCgyGkIvtdgw, matches_xtEppuDcq6NTpHRJimET8g_2, 1, ((NI) 0));
															if (!(T110_ == ((NI) -1))) goto LA111_;
															goto LA101;
														}
														LA111_: ;
														nimln_(23, "desktop_parser_nim.nim");
														T113_ = (NimStringDesc*)0;
														T113_ = name_QBA15VCUqOaVIF7pPjoJig_2; name_QBA15VCUqOaVIF7pPjoJig_2 = copyStringRC1(matches_xtEppuDcq6NTpHRJimET8g_2[(((NI) 0))- 0]);
														if (T113_) nimGCunrefNoCycle(T113_);
														nimln_(24, "desktop_parser_nim.nim");
														{
															if (!((name_QBA15VCUqOaVIF7pPjoJig_2 ? name_QBA15VCUqOaVIF7pPjoJig_2->Sup.len : 0) == ((NI) 0))) goto LA116_;
															goto LA101;
														}
														LA116_: ;
														nimln_(25, "desktop_parser_nim.nim");
														{
															NI T120_;
															T120_ = (NI)0;
															T120_ = find_SG5PU3DKAXRWI7vCeKQOCQ_2re(file_ltpyxdRnkwZ4h3HRLHHKNw_2, execPattern_umckWp8Z39aRjyxuzyRpR9cA, matches_xtEppuDcq6NTpHRJimET8g_2, 1, ((NI) 0));
															if (!(T120_ == ((NI) -1))) goto LA121_;
															goto LA101;
														}
														LA121_: ;
														nimln_(26, "desktop_parser_nim.nim");
														T123_ = (NimStringDesc*)0;
														T123_ = exec_VvPIpxxrGablvcaz7nQNGA_2; exec_VvPIpxxrGablvcaz7nQNGA_2 = copyStringRC1(matches_xtEppuDcq6NTpHRJimET8g_2[(((NI) 0))- 0]);
														if (T123_) nimGCunrefNoCycle(T123_);
														nimln_(27, "desktop_parser_nim.nim");
														{
															if (!((exec_VvPIpxxrGablvcaz7nQNGA_2 ? exec_VvPIpxxrGablvcaz7nQNGA_2->Sup.len : 0) == ((NI) 0))) goto LA126_;
															goto LA101;
														}
														LA126_: ;
														nimln_(28, "desktop_parser_nim.nim");
														asgnRefNoCycle((void**) (&exec_VvPIpxxrGablvcaz7nQNGA_2), replace_XTFad3adT9ckW2xJiSYMhMw(exec_VvPIpxxrGablvcaz7nQNGA_2, argPattern_0utS3ILD5VWCsdlXu6g89aQ, ((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_22)));
														nimln_(30, "desktop_parser_nim.nim");
														memset((void*)T128_, 0, sizeof(T128_));
														T128_[0] = copyString(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_23));
														T128_[1] = copyString(name_QBA15VCUqOaVIF7pPjoJig_2);
														T128_[2] = copyString(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_24));
														T128_[3] = copyString(exec_VvPIpxxrGablvcaz7nQNGA_2);
														T128_[4] = copyString(((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_25));
														echoBinSafe(T128_, 5);
														execFile_GbPldOFJWq0i88ldXmT74w_2 = 0;
														nimln_(31, "desktop_parser_nim.nim");
														T129_ = (NimStringDesc*)0;
														T129_ = rawNewString(name_QBA15VCUqOaVIF7pPjoJig_2->Sup.len + 8);
appendString(T129_, ((NimStringDesc*) &TM_Y9cGof9b2sgVva5jpid59aDNQ_26));
appendString(T129_, name_QBA15VCUqOaVIF7pPjoJig_2);
														execFile_GbPldOFJWq0i88ldXmT74w_2 = open_hqzpWQbdA2B8l9a6wwNoP4g(T129_, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
														nimln_(32, "desktop_parser_nim.nim");
														write_c4mGyJBvK73pdM22jiweKQ(execFile_GbPldOFJWq0i88ldXmT74w_2, exec_VvPIpxxrGablvcaz7nQNGA_2);
														nimln_(33, "desktop_parser_nim.nim");
														close_BWnr8V7RERYno9bIdPmw8Hw_2(execFile_GbPldOFJWq0i88ldXmT74w_2);
													} LA101: ;
												}
												LA32_: ;
											} LA23: ;
										}
									} LA21: ;
									popSafePoint();
								}
								else {
									popSafePoint();
									setFrame((TFrame*)&FR_);
								}
								{
									int T132_;
									nimln_(800, "os.nim");
									T132_ = (int)0;
									T132_ = closedir(d);
									T132_;
								}
								if (TM_Y9cGof9b2sgVva5jpid59aDNQ_15.status != 0) reraiseException();
							}
							LA18_: ;
						}
					} LA9: ;
					nimln_(2203, "system.nim");
					{
						if (!(((NI) 1) <= ((NI) (i)))) goto LA135_;
						goto LA6;
					}
					LA135_: ;
					nimln_(2204, "system.nim");
					TM_Y9cGof9b2sgVva5jpid59aDNQ_31 = addInt(i, ((NI) 1));
					if (TM_Y9cGof9b2sgVva5jpid59aDNQ_31 < 0 || TM_Y9cGof9b2sgVva5jpid59aDNQ_31 > 1) raiseOverflow();
					i = (NI)(TM_Y9cGof9b2sgVva5jpid59aDNQ_31);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, desktop_parser_nimDatInit000)(void) {
NTI_Re75IspeoxXy2oCZHwcRrA_.size = sizeof(tyArray_Re75IspeoxXy2oCZHwcRrA);
NTI_Re75IspeoxXy2oCZHwcRrA_.kind = 16;
NTI_Re75IspeoxXy2oCZHwcRrA_.base = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
NTI_Re75IspeoxXy2oCZHwcRrA_.flags = 2;
NTI_nHXaesL0DJZHyVS07ARPRA_.size = sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA);
NTI_nHXaesL0DJZHyVS07ARPRA_.kind = 16;
NTI_nHXaesL0DJZHyVS07ARPRA_.base = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
NTI_nHXaesL0DJZHyVS07ARPRA_.flags = 2;
}

